# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root@123
  host: localhost

development:
  <<: *default
  database: reimbursement_portal_development

test:
  <<: *default
  database: reimbursement_portal_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: reimbursement_port
  username: root
  password: root@123
  host: localhost
